server:
  port: 8080
  servlet:
    context-path: /demo
  application:
    name: demo
demo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: datacenter
    jdbc-url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
spring:
  thymeleaf:
    prefix: classpath:/html/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'group'
      paths-to-match: '/**'
      packages-to-scan: com.test.demo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn